apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - pods:
      metric:
        name: packets-per-second
      target:
        type: AverageValue
        averageValue: 1k
    type: Pods
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: php-apache